apiVersion: v1
kind: Namespace
metadata:
  name: crypto-watcher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-watcher-service
  namespace: crypto-watcher
spec:
  selector:
    matchLabels:
      app: crypto-watcher-service
  template:
    metadata:
      labels:
        app: crypto-watcher-service
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork:  true
      terminationGracePeriodSeconds: 60
      containers:
        - name: crypto-watcher
          image: crypto-watcher:1.0.0